[project]
name = "jukebot"
version = "0.0.1"
description = "A Discord bot for playing Neopets music in voice channels."
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "discord-py[voice, speed]",
    "python-dotenv>=1.1.1",
]
